#!/usr/bin/env python

from argparse import ArgumentParser
from sys import exit
from os.path import isfile
from tempfile import NamedTemporaryFile

def optimize(infile, outfile, aggressive=False):
    command = [
        "optipng",
        "-strip", "all"
        "-fix",
        "-i0",
        "-o7",
        -out", outfile
    ]

   if agressive:
       command += ["-zm1-9"]

def compress(infile, iterations=5):
    command = [
      "advdef",
      "-z",
      "-4",
      -i", iterations,
      infile
    ]

def main(args):
    if not isfile(args["infile"]):
        print("{} isn't a file. Aborting.".format(args["infile"]))
        exit()

if __name__ == "__main__":
    parser = ArgumentParser(prog="png-squeeze", description="An aggressive PNG optimizer")
    parser.add_argument("-i", "--infile", required=True, help="Input file")

    main(vars(parser.parse_args()))
