#!/usr/bin/env python

from argparse import ArgumentParser
from sys import exit
from os.path import isfile
from tempfile import NamedTemporaryFile
from subprocess import call
from shutil import copyfile

def optimize(infile, outfile, level=0):
    optimization_levels = {
        0: ["-o3"],
        1: ["-o5"],
        2: ["-o7"],
        3: ["-o7", "-zm1-9"]
    }

    command = [
        "optipng",
        "-strip", "all",
        "-fix",
        "-i0",
        "-clobber",
        "-out", outfile,
        infile
    ]

    if level in optimization_levels:
      command += optimization_levels[level]

    call(command)

def compress(infile, iterations=5):
    command = [
        "advdef",
        "-z",
        "-4",
        "-i", str(iterations),
        infile
    ]

    call(command)

def main(args):
    infile = args["infile"]

    if args["outfile"]:
        outfile = args["outfile"]
    else:
        outfile = infile

    if not isfile(infile):
        print("{} isn't a file. Aborting.".format(infile))
        exit()

    with NamedTemporaryFile() as tempfile:
        temp = tempfile.name

        optimize(infile, temp)
        compress(temp)

        copyfile(temp, outfile)

if __name__ == "__main__":
    parser = ArgumentParser(prog="png-squeeze", description="An aggressive PNG optimizer")
    parser.add_argument("-i", "--infile", required=True, help="Input file")
    parser.add_argument("-o", "--outfile", required=False, help="Output file")

    main(vars(parser.parse_args()))
